### PR TITLE
V1.0.0

### PR DESCRIPTION
**Pull request by cat-haines**
@bbharris @blinkman2k

### CODE REVIEW

**Comment by blindman2k** [comment]
Nice job on the README. I would recommend adding a bit of information about the memory and storage requirements. For small objects they are insignificant but for large objects they need to be considered and planned for.

**Comment by cat-haines** [comment]
Do you think it's worth adding a function to determine the size of an object if it serialized?

It should run quite a bite faster (i suspect time would be insignificant compared to the serialize function) as it wouldn't need to manipulate blobs.

**Comment by blindman2k** [comment]
It sure wouldn't hurt nor would it be that hard.

**Comment by cat-haines** [comment]
Any other comments on this PR, or are we happy to merge?

**Comment by blindman2k** [comment]
It looks ok but I will test it soon.

**Pull request merged**
